chore: upload arficats to github

diff --git a/.github/workflows/beekeeper.yml b/.github/workflows/beekeeper.yml
--- a/.github/workflows/beekeeper.yml
+++ b/.github/workflows/beekeeper.yml
@@ -68,6 +68,8 @@ jobs:
       - name: Test pingpong
         id: pingpong
         run: timeout ${TIMEOUT} bash -c 'until beekeeper check --cluster-name local-dns --checks ci-pingpong; do echo "waiting for pingpong..."; sleep .3; done'
+      - name: Always FAIL
+        run: exit 1 
       - name: Test fullconnectivity
         id: fullconnectivity
         run: timeout ${TIMEOUT} bash -c 'until beekeeper check --cluster-name local-dns --checks=ci-full-connectivity; do echo "waiting for full connectivity..."; sleep .3; done'
@@ -105,14 +107,21 @@ jobs:
         run: timeout ${TIMEOUT} beekeeper check --cluster-name local-dns --checks ci-postage
       - name: Debug workflow if failed
         if: failure()
-        run: |
-          export BUCKET_NAME=beekeeper-artifacts
-          export AWS_ACCESS_KEY_ID=${{ secrets.DO_AWS_ACCESS_KEY_ID }}
-          export AWS_SECRET_ACCESS_KEY=${{ secrets.DO_AWS_SECRET_ACCESS_KEY }}
-          export AWS_EC2_METADATA_DISABLED=true
-          export AWS_ENDPOINT=fra1.digitaloceanspaces.com
-          export VERTAG=$(< /dev/urandom tr -dc A-Z-a-z-0-9 2> /dev/null | head -c15)
           bash .github/bin/beekeeper_artifacts.sh
+      - uses: actions/upload-artifact@v3
+        with:
+          name: debug-dump
+          path: dump/
+      - name: Debug workflow if failed
+        # if: failure()
+        run: |
+          # export BUCKET_NAME=beekeeper-artifacts
+          # export AWS_ACCESS_KEY_ID=${{ secrets.DO_AWS_ACCESS_KEY_ID }}
+          # export AWS_SECRET_ACCESS_KEY=${{ secrets.DO_AWS_SECRET_ACCESS_KEY }}
+          # export AWS_EC2_METADATA_DISABLED=true
+          # export AWS_ENDPOINT=fra1.digitaloceanspaces.com
+          # export VERTAG=$(< /dev/urandom tr -dc A-Z-a-z-0-9 2> /dev/null | head -c15)
+          # bash .github/bin/beekeeper_artifacts.sh
           export FAILED='no-test'
           if ${{ steps.pingpong.outcome=='failure' }}; then FAILED=pingpong; fi
           if ${{ steps.fullconnectivity.outcome=='failure' }}; then FAILED=fullconnectivity; fi
